# Generated by Django 5.2.8 on 2025-12-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_film_plakat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='plakat',
        ),
        migrations.AddField(
            model_name='film',
            name='plakat_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
