# Generated by Django 5.2.8 on 2025-12-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_film_plakat_film_plakat_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='plakat_url',
        ),
        migrations.AddField(
            model_name='film',
            name='plakat',
            field=models.ImageField(blank=True, null=True, upload_to='plakaty/'),
        ),
    ]
