# Generated by Django 5.2.8 on 2025-12-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_film_plakat_url_film_plakat'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='gatunek',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='kraj_pochodzenia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='reżyser',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='zwiastun_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
