# Generated by Django 5.2.8 on 2025-12-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_seans_rezerwacja'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
    ]
