# Generated by Django 6.0 on 2025-12-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
