# Generated by Django 6.0 on 2025-12-23 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_recenzja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzja',
            name='ocena',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
